### ISSUE TITLE
Change the rtp path / set rtp lead into Error

### ISSUE THREAD

**Issue by leiming** [gmarik/Vundle.vim#547]
I use the follow command to set up Vundle.vim
```bash
# change the `bundle` to `other_bundle`
it clone https://github.com/gmarik/Vundle.vim.git ~/.vim/other_bundle/Vundle.vim
```

And, this is my `~/.vimrc` : 

```vim
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/other_bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'kien/ctrlp.vim', {'rtp': 'vim/'}

call vundle#end()            " required
filetype plugin indent on    " required

```

Now, `PluginInstall` lead into Error

![image](https://cloud.githubusercontent.com/assets/2059859/5561460/66a26a08-8e15-11e4-91b4-50cb9c716ec7.png)

**Comment by jdevera** [comment]
Your setup is incorrect and will bring you all sorts of trouble.
You are cloning Vundle into some location, then adding that to the rtp but not telling Vundle about in when calling `#begin`. This will result in a second copy of Vundle being installed, and updated, on the standard location `~/.vim/bundle`. And then both are loaded and it can result in all sort of weird problems.

So you have to either store all your plugins in the same place where Vundle is, and you do this by passing the location to `vundle#begin`, or you remove the `Plugin 'Vundle.vim'` line so that Vundle does not install a second copy.

Please report back.

**Comment by leiming** [comment]
The problem still exists.

I use the command to clone 
```bash
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
```

And `.vimrc`:

```vim 
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
" Plugin 'gmarik/Vundle.vim'

Plugin 'tpope/vim-fugitive'
Plugin 'kien/ctrlp.vim', {'rtp': 'vim/'}

call vundle#end()            " required
filetype plugin indent on    " required
syntax on
```

It leads to the same error.

The aim of using `rtp` params is to use the different location of plugins. the latest version cannot support that whereas eithor d690c777f167479a2b9575ab78feb9683991ea42 or  https://github.com/gmarik/Vundle.vim/pull/422  is working.

**Comment by gmarik** [comment]
using [`vundle#rc('~/some/path')`](https://github.com/gmarik/Vundle.vim/blob/master/autoload/vundle.vim#L62-L68) lets you set `~/some/path` as a base dir for your bundles.  If I understand you correctly. Unfortunately it's a deprecated approach.

**Comment by leiming** [comment]
thank @gmarik for the prompt reply. Could you give me a sample that Vundle.vim support different base directories, or a method (like rtp) to locate some plugins outer of the base dir?

**Comment by gmarik** [comment]
@leiming it's in [`test/vimrc`](https://github.com/gmarik/Vundle.vim/blob/master/test/vimrc#L21-L23)

**Comment by jdevera** [comment]
@leiming you are misusing the `rtp` parameter of the `Plugin` command. `kien/ctrlp.vim` is a regular plugin and the repository is structured to be used directly.

This `rtp` exists so that you can use Vundle with some repositories that are not themselves a vim plugin but rather *contain* one in some subdirectory. With `rtp` we tell Vundle in which directory, relative to the root of the repository, the Vim plugin is. The `vim` directory you are passing does not exist in `kien/ctrlp.vim`, therefore you get the missing plugin error.

As stated before, Vundle *does not* support having plugins in different places.

Please remove that `rtp` parameter and report back.

**Comment by jdevera** [comment]
Also, @gmarik, vundle#begin has the same interface as vundle#rc so specifying the base for plugins can still be done.

**Comment by gmarik** [comment]
> vundle#begin has the same interface as

@jdevera i'm far behind you guys! :) Good catch!

**Comment by gmarik** [comment]
@leiming we're closing this issue, feel free to comment if you have more questions.

**Comment by leiming** [comment]
Thank @gmarik @jdevera very much.

Would you support `name` parameter https://github.com/gmarik/Vundle.vim/pull/422#issuecomment-39420036 in future so that I will be compatible with my out-of-date plugin's structure like https://github.com/gmarik/Vundle.vim/pull/422#issue-30569959 ?
