### ISSUE TITLE
How to use Vundle to install plugins from sourceforge or zipfiles

### ISSUE THREAD

**Issue by peidong** [gmarik/Vundle.vim#567]
Not all vim plugins are available from github. I need to install plugins by downloading zips from other websites. How to manage those vim plugins via vundle?

**Comment by Shougo** [comment]
Please explain the examples plugins.
If it is important plugins, it is worth to implement.

**Comment by jdevera** [comment]
All plugins from vim.org are available on github through the http://vim-scripts.org/ project. Perhaps not the development versions, if someone decides to handle that outside git, but the published versions are available. That project is there to support tools like ours.

Vundle is intended to be a simple tool, and it's git centric because that allows us to be simple.

Also please note some sourceforge projects run on git, therefore you can use the full git repo url with Vundle (git centric, not github centric), for instance, for vim-latex (although there is a github mirror):

```viml
Plugin 'git://git.code.sf.net/p/vim-latex/vim-latex'
```

Supporting downloading zips takes away much of that intended simplicity and all we get get in exchange is to use some plugins that are not published even on vim.org.

I'm sorry to say we won't be implementing this feature any time soon.

However, there is an option for you to *load* these non-git plugins via Vundle (but not *update* them):

Say you have a plugin foobar.zip that is not available anywhere as a git repository. Unzip it to your `~/.vim/bundle/` directory so that it takes its own subdir, e.g., `~/.vim/bundle/foobar`. Then use this line in your `.vimrc`:

```viml
Plugin 'foobar', { 'pinned' : 1 }
```

This tells Vundle this plugin should not be tried to be updated, so no git operations will run on it.

**Comment by peidong** [comment]
Is those two lines the same?

1. Plugin 'vim-latex/vim-latex'
2. Plugin 'git://git.code.sf.net/p/vim-latex/vim-latex'

I am confused about their difference.

**Comment by jdevera** [comment]
Not really, but for this particular case, probably yes :smile: 

1. Fetches from https://github.com/vim-latex/vim-latex
2. Fetches from git://git.code.sf.net/p/vim-latex/vim-latex

I think one is a mirror of the other, so it should give you the same **in this particular case**

**Comment by jdevera** [comment]
These are the rules:
  - `Plugin 'foo'` fetches from github.com/vim-scripts/foo
  - `Plugin 'bar/foo'` fetches from github.com/bar/foo
  - `Plugin 'git://mygitrepos/foobarbaz' fetches from exactly that url
