### ISSUE TITLE
1df432a breaks vundle

### ISSUE THREAD

**Issue by vtts** [gmarik/Vundle.vim#568]
the latest Vundle fails with the following error:

> $ (cd ~/.vim/bundle/vundle/ && git rev-parse HEAD)
7d9b10874e374f0db4ae47aa55e49033174bbf50

> $ vim +BundleInstall!
Error detected while processing function vundle#installer#new:
line   13:
No bundles were selected for operation

Check out to 1df432aecfc0dacd93a1da0938830206f418fd66:

> $ (cd ~/.vim/bundle/vundle/ && git checkout 1df432aecfc0dacd93a1da0938830206f418fd66 -b bad && git rev-parse HEAD)
Switched to a new branch 'bad'
1df432aecfc0dacd93a1da0938830206f418fd66

> $ vim +BundleInstall!
Error detected while processing function vundle#installer#new:
line   13:
No bundles were selected for operation

Drop 1df432a:
> $ (cd ~/.vim/bundle/vundle/ && git checkout 1df432aecfc0dacd93a1da0938830206f418fd66^ -b good && git rev-parse HEAD)
Switched to a new branch 'good'
a864467285fc419c5f652c740137fbfb8ffeaa32

> $ vim +BundleInstall!
Now it works well.

My vim is version 7.4.475
and my .vimrc:

> " === start vundle config === "
set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()           " required
Plugin 'gmarik/vundle'
call vundle#end()            " required
filetype plugin indent on    " required
" === end vundle config === "
filetype plugin on    " Enable filetype-specific plugins

**Comment by jdevera** [comment]
Interesting, it works well for me.

I notice that you have these conflicting lines in your vimrc:

```
set rtp+=~/.vim/bundle/Vundle.vim
```
and 
```
Plugin 'gmarik/vundle'
```

This is going to give you two versions of Vundle, one under `~/.vim/bundle/Vundle.vim` and another one under `~/.vim/bundle/vundle`. Only the latter gets updated, but since we load scripts on demand, you end up with a mixture of different versions and that always causes trouble.

The repository was renamed at some point from `vundle` to `Vundle.vim` and since github keeps both names operational a lot of users have these kinds of mixes, unfortunately.

So please consolidate, stick to one name, preferably `Vundle.vim` since it's the current name, and report back.

**Comment by vtts** [comment]
Hi jdevera,

You're right, it's only reproducible in the situation of mixed directory names. After changed to the consolidate name, everything works well.

> $ cat ~/.vimrc
...
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin() " required
Plugin 'gmarik/Vundle.vim' " changed from 'gmarik/vundle' which is differ from Vundle.vim
...

$ ls ~/.vim/bundle/
Vundle.vim

If you're not interested in why it fails in the mixed case, you (or I) can close this issue.

**Comment by jdevera** [comment]
Thanks for reporting back. I'll close it, then, since this is an unsupported scenario and no effort will be devoted to fixing bugs (or non-bugs) that can come from it.
