### ISSUE TITLE
update local plugin that is not yet commited

### ISSUE THREAD

**Issue by rudrab** [gmarik/Vundle.vim#571]
Hi,
I am trying to update a the bundle for a plugin lives locally in my machine. 
But it seems bundle update does not work until that is committed (very fair for git).
But then, to update my plugin, my workflow is write->commit->PluginUpdate->if it works, fine-> else in local file, git revert->pluginupdate.

Is this how this works?
Or I am just missing something silly?

Other work around is to edit the plugin in bundle directly and then copy it to the local dir....but..then this is not what we should do with git, right?

This is surely not an "issue", but failed to get help in #vim irc

**Comment by av3r4ge** [comment]
For development I just put a symbolic link from my bundles directory to my development directory.
You sould, of course, add it anyway to your .vimrc for Vundle to include it in your rtp.

There might be a better way, but this is the workaround I've found for developement.

**Comment by jdevera** [comment]
If you want to develop a plugin and test it while you are at it, you can use a combination of symlinks and the 'pinned' option.

So let's say you write your plugin in `~/dev/vim-foo`. Now simlink it from the bundle directory:

```
ln -s ~/dev/vim-foo ~/.vim/bundle/vim-foo
```

Now add this to your vimrc:

```viml
Plugin 'vim-foo' , {'pinned' : 1}
```

Now Vundle will load this plugin but it will never do any git operations on it (pinned).

So you can do your development and test immediately without having to commit.

Otherwise you have to do what you are doing now. By the way, if you do git revert, you are undoing all your changes in the form of a new reverse commit. Maybe you want to try doing `git reset HEAD^` to undo the latest commit and leave all its contents in your working copy. If you haven't shared your repo with other developers, this is cleaner than git revert. You can also do `git reset --hard HEAD^` but then the committed changes are dropped completely, it's basically as if the last commit never happened.

Closing, but feel free to comment further.

**Comment by rudrab** [comment]
Hi....can I do the "pinned" with git's branch (i.e. development branch, not master)?
