### ISSUE TITLE
Making changes to a file:/// repo results in git errors

### ISSUE THREAD

**Issue by JESii** [gmarik/Vundle.vim#585]
I have a local repo `Plugin 'file:///Users/yc98js1/dev/vim-cucumber'` where I'm trying out some changes to the plugin. I want to keep making changes here without updating the corresponding github repo where I've already added documentation and I want to keep that repo clean until my local work is finished.
However, I can't seem to make this work. For example, I created a new branch and PluginUpdate worked the first time. But after that with more changes, I get the error `"Your local changes to the following files would be overwritten..."`. Going back to the master branch results in the same situation.
The only way I've been able to resolve this is by manually deleting the `~/.vim/bundle/vim-cucumber`directory and then doing another PluginUpdate command.
How should I be using this file repo? Thanks.

**Comment by JESii** [comment]
So... I removed the file:/// repo and replaced it with my github version `'https://github.com/JESii/vim-cucumber.git'` and did a PluginInstall; that worked fine with no errors.
However, the old file-based version is still installed in vim and I had to again remove the vim-cucumber directory and do another PluginInstall.

**Comment by jdevera** [comment]
Where did you create the branch?

**Comment by JESii** [comment]
In my local file repo

Big fingers; tiny keyboard... Please excuse typos and those crazy auto corrections.

**Comment by jdevera** [comment]
I'm not sure I understood the whole problem, let me tell you how Vundle is supposed to work:

If you do `Plugin 'file:///yaddayadda'` then that repo is taken as remote. Vundle will make a clone, and will only use the master branch. You can create any branches you want in that repo, but Vundle will see none of it, only runs on master.

You say you created a new branch, in `/yaddayadda`, not in `~/.vim/bundle/yaddayadda`. About this Vundle does not care, as long as it keeps on getting the master branch it is happy. If you switch to a different branch in anything that is under `~/.vim/bundle`, then you'd be breaking Vundle assumptions and thinks will break. Vundle *owns* all these directories and they should not be fiddled with :)

That error you mention about the local changes happens when you are switching branches. If you saw that in Vundle it means you are touching the repos owned by Vundle. If you saw that in your development location it means you should either commit your pending changes or stash them before you switch branches.

The way this is supposed to work is: Whatever changes you want Vundle to pick up, they need to be merged in the master branch of your development repo, so the next next PluginUpdate will pick up those changes.

Please let me know if this helped, or if you are following these steps and still getting some errors.

**Comment by JESii** [comment]
Thanks very much,@jdevera; that really helps. I'll go back and rework things and I'm guessing that will take care of the problems.

**Comment by JESii** [comment]
OK, @jdevera... I've gone back, started over with a new repo and tried to make changes. I still cannot get it to work so here's what I've done and the results I get.

**Initial creation of repo on file system**
1) I forked the Chris Toomey's vim-conflicted repo into https://github.com/JESii/vim-conflicted
2) I cloned my repo into ~/dev/vimscripts/vim-conflicted
3) I made a change to plugin.vim
4) I committed to the change directly to master
5) I pushed the change to my github repo
6) I modified my .vimrc to point to the file::/// directory

**PluginUpdate**
1) PluginUpdate gives the following errors:
[2015-04-12 08:29:08] Plugin file:///Users/jseidel/dev/vimscripts/vim-conflicted
[2015-04-12 08:29:08] $ cd '/Users/jseidel/.vim/bundle/vim-conflicted' && git pull && git submodule update --init --recursive
[2015-04-12 08:29:08] > Uplugin/conflicted.vim
[2015-0 4-12 08:29:08] > Pull is not possible because you have unmerged files.
[2015-04-12 08:29:08] > Please, fix them up in the work tree, and then use 'git add/rm <file>'
[2015-04-12 08:29:08] > as appropriate to mark resolution and make a commit.

2) git status gives the following:
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

3) git pull origin master gives the following:
From https://github.com/JESii/vim-conflicted
 * branch            master     -> FETCH_HEAD
 Already up-to-date.

4) Running the PluginUpdate commands manually in my directory yields no errors:

jseidel@EDP28:[vim-conflicted->master]~/dev/vimscripts/vim-conflicted$ git pull
Already up-to-date.
jseidel@EDP28:[vim-conflicted->master]~/dev/vimscripts/vim-conflicted$ git submodule update --init --recursive
jseidel@EDP28:[vim-conflicted->master]~/dev/vimscripts/vim-conflicted$ 

I'm not sure what to try at this point...thanks...jon

**Comment by jdevera** [comment]
Seems like you have those uncommittted changes in `~/.vim/bundle/vim-conflicted`. So try commenting that `Plugin` line out on your vimrc, then run a `PluginClean`, and then uncomment the line again and do a `PluginInstall`.

**Comment by JESii** [comment]
Awesome; that did the trick! Thanks so much for your help.
